# Credits

This is heavily influenced or copied from https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [3]:
import torch

Construct a 5x3 matrix, uninitialized

In [4]:
x = torch.Tensor(5, 3)
print(x)
print(x.size())

tensor([[-2.4462e-16,  3.0920e-41,  3.7835e-44],
        [ 0.0000e+00,         nan,  3.0920e-41],
        [ 1.3733e-14,  6.4069e+02,  4.3066e+21],
        [ 1.1824e+22,  4.3066e+21,  6.3828e+28],
        [ 3.8016e-39,  3.0920e-41, -7.0022e-17]])
torch.Size([5, 3])


Construct a randomly initialized matrix

In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3575, 0.1990, 0.2721],
        [0.2506, 0.2888, 0.0312],
        [0.3034, 0.3418, 0.6764],
        [0.9314, 0.9175, 0.6045],
        [0.8431, 0.1713, 0.6799]])


Get its size

In [6]:
print(x.size())

torch.Size([5, 3])


**NOTE** `torch.Size` is in fact a tuple, so it supports the same operations

In [7]:
x[1:3] = 2
print(x)

tensor([[0.3575, 0.1990, 0.2721],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.9314, 0.9175, 0.6045],
        [0.8431, 0.1713, 0.6799]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [8]:
# Make a tensor of size (2, 17)
a = torch.Tensor(2, 17)
print(a)

tensor([[-2.3631e-16,  3.0920e-41,  0.0000e+00,  0.0000e+00,  1.4013e-45,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00, -2.4425e-16,  3.0920e-41,  0.0000e+00,
          0.0000e+00,  1.4013e-45],
        [ 0.0000e+00,  4.2039e-45,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  1.4013e-45,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])


In [9]:
# Make a torch.FloatTensor of size (3, 1)
a = torch.FloatTensor(3, 1)
print(a)

tensor([[-2.4461e-16],
        [ 3.0920e-41],
        [ 2.3694e-38]])


In [10]:
# Make a torch.LongTensor of size (5, 2, 1)
# fill the entire tensor with 7s
a = torch.LongTensor(5, 2, 1)
a[:] = 7
print(a)

tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])


In [11]:
# Make a torch.ByteTensor of size (5,)
# fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]
a = torch.ByteTensor(5,)
a[:] = 0
a[1:4] = 1
print(a)

tensor([0, 1, 1, 1, 0], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [12]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.3278, 0.3454, 0.9701],
        [2.4765, 2.8493, 2.0672],
        [2.6535, 2.9823, 2.7446],
        [1.0383, 0.9618, 1.3547],
        [1.2540, 1.1079, 0.7706]])


### 2.2 Addition: syntax 2

In [13]:
print(torch.add(x, y))

tensor([[1.3278, 0.3454, 0.9701],
        [2.4765, 2.8493, 2.0672],
        [2.6535, 2.9823, 2.7446],
        [1.0383, 0.9618, 1.3547],
        [1.2540, 1.1079, 0.7706]])


### 2.3 Addition: giving an output tensor

In [14]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.3278, 0.3454, 0.9701],
        [2.4765, 2.8493, 2.0672],
        [2.6535, 2.9823, 2.7446],
        [1.0383, 0.9618, 1.3547],
        [1.2540, 1.1079, 0.7706]])


### 2.4 Addition: in-place

adds `x`to `y`

In [15]:
y.add_(x)
print(y)

tensor([[1.3278, 0.3454, 0.9701],
        [2.4765, 2.8493, 2.0672],
        [2.6535, 2.9823, 2.7446],
        [1.0383, 0.9618, 1.3547],
        [1.2540, 1.1079, 0.7706]])


**NOTE** Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [16]:
print(x[:, 1])

tensor([0.1990, 2.0000, 2.0000, 0.9175, 0.1713])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [17]:
a = torch.rand(2, 3) * 10
b = torch.rand(2, 3) * 10
# c = a * b
c = torch.mul(a, b)
print(a,'\n', b ,'\n',c)
a.mul_(b)
print(a)
print("-----------")
c = torch.div(a, b)
print(a,'\n', b ,'\n',c)
a.div_(b)
print(a)

tensor([[1.7010, 4.0196, 4.4886],
        [2.0340, 2.2426, 6.3041]]) 
 tensor([[8.4045, 5.4680, 3.8748],
        [0.7970, 4.0636, 1.4464]]) 
 tensor([[14.2962, 21.9790, 17.3923],
        [ 1.6212,  9.1131,  9.1184]])
tensor([[14.2962, 21.9790, 17.3923],
        [ 1.6212,  9.1131,  9.1184]])
-----------
tensor([[14.2962, 21.9790, 17.3923],
        [ 1.6212,  9.1131,  9.1184]]) 
 tensor([[8.4045, 5.4680, 3.8748],
        [0.7970, 4.0636, 1.4464]]) 
 tensor([[1.7010, 4.0196, 4.4886],
        [2.0340, 2.2426, 6.3041]])
tensor([[1.7010, 4.0196, 4.4886],
        [2.0340, 2.2426, 6.3041]])


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [18]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [19]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.

In [20]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [21]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

In [22]:
a = torch.ones(5, 2)
b = a.numpy()
a.mul_(2)
print(a)
print(b)
c = torch.from_numpy(b)
a.mul_(2)
print(a, '\n', b, '\n', c)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])
[[2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]]
tensor([[4., 4.],
        [4., 4.],
        [4., 4.],
        [4., 4.],
        [4., 4.]]) 
 [[4. 4.]
 [4. 4.]
 [4. 4.]
 [4. 4.]
 [4. 4.]] 
 tensor([[4., 4.],
        [4., 4.],
        [4., 4.],
        [4., 4.],
        [4., 4.]])


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [23]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # this is meant as a tensor to be run on the GPU.
    # the .cuda() does this to any parameter it is applied to
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

CUDA not available on your machine.
